### ISSUE TITLE
Accent color in flyout doesn't change with system accent color.

### ISSUE THREAD

**Issue by Cyberdroid1** [ShankarBUS/ModernFlyouts#38]
![image](https://user-images.githubusercontent.com/51435948/93424537-dac09c80-f8d5-11ea-8606-a34b1c01e7be.png)

![image](https://user-images.githubusercontent.com/51435948/93428243-bae0a700-f8dc-11ea-92d9-5cb652156c42.png)

Restarting fixes the issue.

**Comment by ShankarBUS** [comment]
So the change in system accent color is not percieved by the app while running, isn't it?

**Comment by Cyberdroid1** [comment]
Yes.

**Comment by ShankarBUS** [comment]
Had this same problem earlier. I fixed it in v0.2.0. But this is occurring again (could be due to repackaging). Thanks for filing this issue. I wouldn't have noticed it on my own 😅🙏

**Comment by ShankarBUS** [comment]
This seems to be a bug in the UI library and has been filed on the corresponding repository - https://github.com/Kinnara/ModernWpf/issues/175

**Comment by ShankarBUS** [comment]
Done! 7aa0c8c31562d9b407f8b628a913e0312a3d77ea

Will be available in v0.6.0

**Comment by ShankarBUS** [comment]
Hey @Cyberdroid1, can you verify whether this issue persists or not**?

Unfortunately our workaround seems to be dummy and there are several issues behind this.

**If you don't mind.

**Comment by Cyberdroid1** [comment]
I have not faced this issue in a while. I will reopen it if this issue happens again. You may close this for now.

**Comment by ShankarBUS** [comment]
It must have been fixed by now.

@Cyberdroid1, sorry for disturbing you 😅.

Could you recheck the behaviour?

**Comment by Cyberdroid1** [comment]
Sadly, the issue is still there.

![image](https://user-images.githubusercontent.com/51435948/96152610-5d1a9b80-0f2a-11eb-9c7d-626886c95997.png)

You can reproduce yourself too.

**Comment by ShankarBUS** [comment]
😔 Thanks for spending your time.

I'll see what I can do.

**Comment by ShankarBUS** [comment]
Hey @Cyberdroid1,

I can't reproduce this even in the store version (v0.7.1).

![image](https://user-images.githubusercontent.com/63704247/97069725-b9974e00-15ef-11eb-94fc-5b860ddebbce.png)

It seemed to be fixed in ModernWpf.
Could you recheck this?

**Comment by Cyberdroid1** [comment]
Yup, I have checked. This is completely fixed now. Thanks!

**Comment by Cyberdroid1** [comment]
You can close this issue now!

**Comment by Samuel12321** [comment]
great thanks @Cyberdroid1
