### ISSUE TITLE
Show which app is playing media in the audio flyout

### ISSUE THREAD

**Issue by Poopooracoocoo** [ShankarBUS/ModernFlyouts#48]
Looks like there's a perfect gap for it! :p
![image](https://user-images.githubusercontent.com/51363864/93713465-76386280-fb9f-11ea-9a83-a6d2fd56b4f2.png)

i have no idea if its possible but would be really neat :D

**Comment by ShankarBUS** [comment]
This feature is already available in **ModernFlyouts**. You can see the sample images as a proof. This app uses `SourceAppUserModelId `to find whether the app is packaged/unpackaged and fetches their name and logos.

I added this feature as a part of #1

Which app is playing that?

That particular application couldn't be providing any identity to find it. Can you inform me so that I can reproduce this issue

**Comment by Poopooracoocoo** [comment]
Oh. I feel stoopid lol. 

I'm playing this in MS Edge. I've waited for a good 10, 15 minutes and it still hasn't shown up.

**Comment by ShankarBUS** [comment]
Oh my god another bug? (<sub>Are ya kidding me</sub>) It works perfectly in my PC.

Anyway, thanks for reporting this pal 🤗.

**Comment by ShankarBUS** [comment]
Bruhhhh! It works for me 😂 (I don't know why I get some bugs in the release version lol)

![image](https://user-images.githubusercontent.com/63704247/93714220-d965cd00-fb7e-11ea-8383-b5943b8f405d.png)

**Comment by Poopooracoocoo** [comment]
closing as this has been fixed with 0.0.5 :)

**Comment by ShankarBUS** [comment]
*v0.5.0.

I didn't fix it TBH. It was already working, I'm confused how it worked for you now.

**Comment by ShankarBUS** [comment]
@Poopooracoocoo,

Feel free to reopen this issue if you experience this again
